services:
  gateway_api:
    build: .
    container_name: gateway_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "5001:8080"
    networks:
      - monitoring_network
    restart: unless-stopped

networks:
  monitoring_network:
    external: true
