apiVersion: v1
kind: Service
metadata:
  name: gateway-api
  namespace: fiap-cloud-games
spec:
  type: NodePort
  selector:
    app: gateway-api
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
